-- MySQL Script generated by MySQL Workbench
-- 10/05/15 15:47:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema granja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema granja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `granja` DEFAULT CHARACTER SET utf8 ;
USE `granja` ;

-- -----------------------------------------------------
-- Table `granja`.`farm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `granja`.`farm` (
  `idFarm` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `users_USER_ID` INT(10) NOT NULL COMMENT '',
  PRIMARY KEY (`idFarm`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `granja`.`chicken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `granja`.`chicken` (
  `idChicken` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `eggs` INT(11) NULL DEFAULT NULL COMMENT '',
  `Farm_idFarm` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idChicken`)  COMMENT '',
  INDEX `fk_Chicken_Farm_idx` (`Farm_idFarm` ASC)  COMMENT '',
  CONSTRAINT `fk_Chicken_Farm`
    FOREIGN KEY (`Farm_idFarm`)
    REFERENCES `granja`.`farm` (`idFarm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `granja`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `granja`.`users` (
  `USER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `USERNAME` VARCHAR(45) NOT NULL COMMENT '',
  `PASSWORD` VARCHAR(45) NOT NULL COMMENT '',
  `ENABLED` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`USER_ID`)  COMMENT '',
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `granja`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `granja`.`user_roles` (
  `USER_ROLE_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `USER_ID` INT(10) UNSIGNED NOT NULL COMMENT '',
  `AUTHORITY` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`USER_ROLE_ID`)  COMMENT '',
  INDEX `FK_user_roles` (`USER_ID` ASC)  COMMENT '',
  CONSTRAINT `FK_user_roles`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `granja`.`users` (`USER_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Table `granja`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `granja`.`users` (
  `USER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `ENABLED` TINYINT(1) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `granja`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `granja`.`user_roles` (
  `USER_ROLE_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(10) UNSIGNED NOT NULL,
  `AUTHORITY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ROLE_ID`),
  INDEX `FK_user_roles` (`USER_ID` ASC),
  CONSTRAINT `FK_user_roles`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `granja`.`users` (`USER_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
